#!/usr/bin/env python3
"""
Hermes Migrate — Export/Import Hermes Agent configurations between hosts.

Exports all Hermes configuration (config.yaml, .env, auth tokens, skills,
cron jobs, memory, channel directory, profiles) into a portable tar.gz archive.
Imports that archive onto a new Hermes instance with conflict detection.

Usage:
    hermes-migrate export [--output PATH] [--redact-secrets] [--no-profiles]
    hermes-migrate import ARCHIVE [--dry-run] [--force] [--target-home PATH]
    hermes-migrate list ARCHIVE
    hermes-migrate diff ARCHIVE
"""

import argparse
import fnmatch
import io
import json
import os
import re
import socket
import subprocess
import sys
import tarfile
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

__version__ = "1.2.0"


# ── Constants ────────────────────────────────────────────────────────────────
# These constants define WHAT gets exported from a Hermes home directory.
# They are the single source of truth — if a new config artifact is added to
# Hermes, it must be listed here (or explicitly excluded) to be handled correctly.
# ──────────────────────────────────────────────────────────────────────────────

# ── Top-level config files ───────────────────────────────────────────────────
# These are individual files at the root of HERMES_HOME that define the
# instance's identity and behavior. They are always included in every export.
CONFIG_FILES = [
    "config.yaml",            # Main Hermes configuration (models, providers, tools, gateway)
    ".env",                   # Environment variables (API keys, secrets, provider tokens)
    "auth.json",              # OAuth tokens and authentication state
    "channel_directory.json", # Mapping of messaging channels (Telegram, Discord, etc.)
    "SOUL.md",                # Agent persona / personality definition
]

# ── Config directories ───────────────────────────────────────────────────────
# These are directories under HERMES_HOME that contain user-created or
# system-managed content. Entire directory trees are exported, minus
# runtime/cache items defined in the per-directory exclude sets below.
CONFIG_DIRS = [
    "skills",                 # Reusable skill definitions (SKILL.md files)
    "memories",               # Persistent agent memory (MEMORY.md, USER.md)
    "cron",                   # Scheduled job definitions
    "plugins",                # Third-party and custom plugins
]

# ── Per-directory exclusions ─────────────────────────────────────────────────
# These files/directories live inside the config directories above but are
# runtime artifacts, not portable configuration. They are skipped during export.

# Items inside skills/ that are regenerated or track local state
SKILLS_EXCLUDE = {
    ".bundled_manifest",      # Regenerated by Hermes on skill install/update
    ".usage.json",            # Local usage statistics (how often each skill is used)
    ".usage.json.lock",       # Lock file for usage tracking
    ".curator_state",         # Skill curator runtime state (not portable)
    ".curator_backups",       # Curator backup archives (large, local only)
}

# Items inside cron/ that are runtime outputs, not job definitions
CRON_EXCLUDE = {
    "output",                 # stdout/stderr logs from cron job runs (bulky, machine-specific)
    ".tick.lock",             # Scheduler tick lock (prevents concurrent runs)
}

# ── Top-level exclusions ─────────────────────────────────────────────────────
# These items at the root of HERMES_HOME are NOT configuration — they are
# runtime state, caches, logs, lock files, session data, or build artifacts.
# Grouped by category for clarity; fnmatch globs (e.g., "config.yaml.bak.*")
# are supported via _should_exclude_top_level().
#
# Categories:
#   Runtime DBs & state   — session/kanban databases, gateway state, process tracking
#   Locks & PIDs           — files that prevent concurrent access, exist only while running
#   Caches                 — model lists, audio/image caches, dev caches
#   Logs & history         — debug logs, shell history
#   Sandboxes & checkpoints— temporary workspaces for code execution
#   Infrastructure         — LSP servers, binaries, hooks, pairing data
#   Backups                — timestamped config backups (.bak.*)
#   Internal state         — install method marker, state snapshots directories
TOP_LEVEL_EXCLUDE = {
    # ── Session & state databases ──
    "sessions",               # Session transcript storage (SQLite + files)
    "state.db",               # Agent state database
    "state.db-shm",           # SQLite shared memory (WAL journal)
    "state.db-wal",           # SQLite write-ahead log (WAL journal)
    "state-snapshots",        # State snapshot archives directory
    "kanban.db",              # Kanban board state database
    "kanban.db-shm",          # SQLite shared memory
    "kanban.db-wal",          # SQLite write-ahead log

    # ── Gateway & process runtime ──
    "gateway.pid",            # Gateway process ID file (alive only while running)
    "gateway.lock",           # Gateway mutex lock (prevents duplicate gateways)
    "gateway_state.json",     # Gateway runtime state (ephemeral)
    "processes.json",         # Background process tracking (ephemeral)
    "auth.lock",              # Authentication mutex lock
    "shell-hooks-allowlist.json", # Runtime shell hook approvals (machine-specific)

    # ── Caches ──
    "cache",                  # General cache directory
    "audio_cache",            # Generated audio files (TTS output)
    "image_cache",            # Generated image files
    "images",                 # Downloaded/embedded images
    "models_dev_cache.json",  # Cached model list (regenerated on next fetch)
    "ollama_cloud_models_cache.json", # Cached Ollama cloud model list

    # ── Logs & history ──
    "logs",                   # Agent log files
    ".hermes_history",        # Shell command history
    "interrupt_debug.log",    # Interrupt/debug trace log

    # ── Sandboxes & workspaces ──
    "checkpoints",            # Agent checkpoint data
    "sandboxes",              # Code execution sandbox directories

    # ── Infrastructure (not portable) ──
    "hermes-agent",           # The Hermes agent installation itself (binaries, venv)
    "lsp",                    # Language server protocol binaries
    "bin",                    # Local binaries
    "hooks",                  # Git hooks and other local hooks
    "pairing",                # Device pairing state (machine-specific)

    # ── Install marker ──
    ".install_method",        # Records how Hermes was installed (local state)

    # ── Backup files (timestamped copies of config) ──
    "config.yaml.bak." + "*", # Backup copies of config.yaml (e.g., config.yaml.bak.20250601)
    ".env.bak." + "*",        # Backup copies of .env
}


def get_hermes_home() -> Path:
    """Resolve HERMES_HOME from environment or default.

    Checks the HERMES_HOME environment variable first (used when Hermes
    is installed at a custom location). Falls back to ~/.hermes if unset.
    """
    return Path(os.environ.get("HERMES_HOME", Path.home() / ".hermes")).expanduser().resolve()


def get_export_name() -> str:
    """Generate a descriptive export filename.

    Format: hermes-export-<hostname>-<YYYYMMDD-HHMMSS>.tar.gz
    This makes it easy to identify which machine and when the export was made.
    """
    hostname = os.uname().nodename
    date_str = datetime.now().strftime("%Y%m%d-%H%M%S")
    return f"hermes-export-{hostname}-{date_str}.tar.gz"


# ── Export ───────────────────────────────────────────────────────────────────
# The export pipeline has three stages:
#   1. MANIFEST BUILDING  — decide which files to include (build_export_manifest)
#   2. ARCHIVE WRITING    — write the tar.gz with metadata and processed content
#   3. REDACTION          — optionally strip secrets from .env files
# ──────────────────────────────────────────────────────────────────────────────

def export_config(
    output_path: Optional[str] = None,
    redact_secrets: bool = False,
    include_profiles: bool = True,
    hermes_home: Optional[Path] = None,
) -> Path:
    """
    Package Hermes configuration into a portable tar.gz archive.

    Parameters:
        output_path     - Where to write the archive (auto-named if None)
        redact_secrets  - If True, replace API keys with [REDACTED] in .env files
        include_profiles- If False, skip named profiles under HERMES_HOME/profiles/
        hermes_home     - Override the Hermes home directory (uses HERMES_HOME env or ~/.hermes)

    Returns the path to the created archive.
    """
    hermes_home = hermes_home or get_hermes_home()

    # ── Validate Hermes home exists ──────────────────────────────────────
    if not hermes_home.exists():
        print(f"ERROR: Hermes home not found at {hermes_home}")
        sys.exit(1)

    # ── Determine output path ────────────────────────────────────────────
    if not output_path:
        output_path = get_export_name()

    output_path = Path(output_path).expanduser().resolve()

    print(f"Hermes home: {hermes_home}")
    print(f"Export to:   {output_path}")

    # ── Stage 1: Build the manifest ─────────────────────────────────────
    # This is the core logic — decides exactly which files and directories
    # to include based on CONFIG_FILES, CONFIG_DIRS, and exclude sets.
    manifest = build_export_manifest(hermes_home, include_profiles)

    if not manifest:
        print("ERROR: No Hermes configuration files found to export.")
        sys.exit(1)

    print(f"\nExporting {len(manifest)} items:")

    # ── Compute archive paths ────────────────────────────────────────────
    # Archive paths are relative to hermes_home.parent so they unpack as
    # .hermes/config.yaml, .hermes/skills/..., etc. on the target host.
    archive_members = []
    for src_path in sorted(manifest):
        arcname = src_path.relative_to(hermes_home.parent)
        # Compute total size for display (recurse into directories)
        size = src_path.stat().st_size if src_path.is_file() else sum(
            f.stat().st_size for f in src_path.rglob("*") if f.is_file()
        )
        print(f"  {arcname}  ({_human_size(size)})")
        archive_members.append((src_path, str(arcname)))

    # ── Build metadata manifest ──────────────────────────────────────────
    # Embedded in the archive as .hermes-migrate-manifest.json so the
    # import side can validate, show metadata, and warn about redacted exports.
    manifest_data = {
        "version": 1,
        "exported_at": datetime.now(timezone.utc).isoformat(),
        "hostname": os.uname().nodename,
        "hermes_home": str(hermes_home),
        "item_count": len(manifest),
        "redacted": redact_secrets,
    }

    # ── Stage 2: Write the tar.gz archive ────────────────────────────────
    print("\nCompressing...")
    with tarfile.open(output_path, "w:gz") as tar:
        # Write the manifest as the very first entry (easy to find and parse)
        manifest_json = json.dumps(manifest_data, indent=2).encode("utf-8")
        info = tarfile.TarInfo(name=".hermes-migrate-manifest.json")
        info.size = len(manifest_json)
        tar.addfile(info, io.BytesIO(manifest_json))

        for src_path, arcname in archive_members:
            if src_path.is_file():
                content = src_path.read_bytes()

                # ── Stage 3 (optional): Redact secrets ──────────────────
                # Only applied to .env files. auth.json is NOT redacted
                # because OAuth tokens follow a different format.
                if redact_secrets and src_path.name == ".env":
                    content = redact_env_content(content)

                # Build tar entry preserving original file metadata
                # but stripping user/group info for portability.
                info = tar.gettarinfo(
                    name=str(src_path),
                    arcname=arcname,
                )
                info.uid = 0
                info.gid = 0
                info.uname = ""
                info.gname = ""
                # For files, set size from the (possibly redacted) content
                if src_path.is_file():
                    info.size = len(content)
                    tar.addfile(info, io.BytesIO(content))
                else:
                    tar.addfile(info)
            else:
                # Directories — add recursively
                tar.add(src_path, arcname=arcname, recursive=True)

    archive_size = output_path.stat().st_size
    print(f"\nDone: {output_path} ({_human_size(archive_size)}")

    # ── Security warning for non-redacted exports ────────────────────────
    if not redact_secrets:
        print("\n*** SECURITY NOTICE ***")
        print("This export CONTAINS your API keys and secrets (.env, auth.json).")
        print("Transfer it securely. Use --redact-secrets to strip them out.")

    return output_path


def build_export_manifest(hermes_home: Path, include_profiles: bool) -> list[Path]:
    """Build the complete list of files and directories to include in the export.

    This function is the heart of the migration tool. It assembles the manifest
    in four passes:

        1. TOP-LEVEL CONFIG FILES  — named files from CONFIG_FILES (config.yaml, .env, etc.)
        2. CONFIG DIRECTORIES       — entire directories from CONFIG_DIRS, with per-directory
                                      exclusions applied (skills, memories, cron, plugins)
        3. PROFILES                 — named profiles under profiles/, each processed
                                      with the same rules as the main Hermes home
        4. CATCH-ALL                — any remaining top-level files not explicitly
                                      excluded, to future-proof against new config artifacts

    Only FILES are collected in the catch-all pass; directories are handled
    by passes 2 and 3. Files matched by TOP_LEVEL_EXCLUDE are always skipped.
    """
    manifest = []

    # ── Pass 1: Top-level config files ──────────────────────────────────
    for fname in CONFIG_FILES:
        fpath = hermes_home / fname
        if fpath.exists():
            manifest.append(fpath)

    # ── Pass 2: Config directories ─────────────────────────────────────
    for dname in CONFIG_DIRS:
        dpath = hermes_home / dname
        if not dpath.exists():
            continue
        _add_dir_contents(manifest, dpath, hermes_home, dname)

    # ── Pass 3: Named profiles ─────────────────────────────────────────
    if include_profiles:
        profiles_dir = hermes_home / "profiles"
        if profiles_dir.exists():
            for profile_dir in sorted(profiles_dir.iterdir()):
                if not profile_dir.is_dir():
                    continue
                _add_profile_contents(manifest, profile_dir, hermes_home)

    # ── Pass 4: Catch-all for unknown top-level files ──────────────────
    # This pass ensures we don't silently miss new config files that were
    # added to Hermes after this tool was written. Rules:
    #   - Skip dotfiles (internal/private state)
    #   - Skip anything in TOP_LEVEL_EXCLUDE (runtime, caches, etc.)
    #   - Skip entries already handled by passes 1-3
    #   - Only include FILES (directories are handled above)
    for entry in sorted(hermes_home.iterdir()):
        if entry.name.startswith("."):
            continue
        if _should_exclude_top_level(entry.name):
            continue
        if entry.name in CONFIG_FILES or entry.name in CONFIG_DIRS:
            continue
        if entry.is_dir() and entry.name == "profiles":
            continue
        # Any other file at top level that isn't excluded — include it
        if entry.is_file():
            manifest.append(entry)

    return manifest


def _add_dir_contents(
    manifest: list,
    dirpath: Path,
    hermes_home: Path,
    dirname: str,
) -> None:
    """Recursively add files from a config directory, filtering out runtime artifacts.

    Applies two layers of filtering:
        1. PER-DIRECTORY EXCLUSIONS — items in SKILLS_EXCLUDE or CRON_EXCLUDE
           (based on dirname). Supports fnmatch wildcards for patterns like
           "config.yaml.bak.*".
        2. LOCK FILES — any file ending in ".lock" is always skipped because
           lock files are runtime noise, never portable configuration.

    Parameters:
        manifest  - The list being built (mutated in place)
        dirpath   - Absolute path to the directory being scanned
        hermes_home- Hermes home (for context, not used directly)
        dirname   - Short name of the directory ("skills", "cron", etc.)
                    used to select the right exclude set
    """
    # Select the exclude set for this directory type
    excludes = {"skills": SKILLS_EXCLUDE, "cron": CRON_EXCLUDE}.get(dirname, set())

    for entry in sorted(dirpath.rglob("*")):
        # Build the path relative to dirpath to check each component
        rel = entry.relative_to(dirpath)
        parts = rel.parts

        # Check if any path component is in the exclude set
        skip = False
        for part in parts:
            if part in excludes:
                skip = True
                break
            # Also check glob-style wildcard patterns (e.g., "*.bak.*")
            for exc in excludes:
                if "*" in exc:
                    if fnmatch.fnmatch(part, exc):
                        skip = True
                        break
            if skip:
                break
        if skip:
            continue

        # Lock files are always runtime noise — never export them
        if entry.name.endswith(".lock"):
            continue

        if entry.is_file():
            manifest.append(entry)


def _add_profile_contents(
    manifest: list,
    profile_dir: Path,
    hermes_home: Path,
) -> None:
    """Add a single named profile's configuration to the manifest.

    A profile mirrors the main Hermes home structure: it can have its own
    config.yaml, .env, skills/, memories/, cron/, and plugins/. This function
    applies the same inclusion rules as the main home.

    Parameters:
        manifest   - The list being built (mutated in place)
        profile_dir- Absolute path to the profile directory (e.g., ~/.hermes/profiles/work)
        hermes_home- Hermes home (for context)
    """
    # Profile-level config files (same set as top-level CONFIG_FILES)
    for fname in CONFIG_FILES:
        fpath = profile_dir / fname
        if fpath.exists():
            manifest.append(fpath)

    # Profile config directories — note "plugins" is added alongside CONFIG_DIRS
    # because profiles can also have their own plugins
    for dname in CONFIG_DIRS + ["plugins"]:
        dpath = profile_dir / dname
        if not dpath.exists():
            continue
        _add_dir_contents(manifest, dpath, hermes_home, dname)

    # Catch-all for any other files in the profile directory
    for entry in sorted(profile_dir.iterdir()):
        if entry.name.startswith("."):
            continue
        if entry.name in CONFIG_FILES or entry.name in CONFIG_DIRS or entry.name == "plugins":
            continue
        if entry.is_file():
            manifest.append(entry)


def _should_exclude_top_level(name: str) -> bool:
    """Check if a top-level entry should be excluded from the export.

    Uses fnmatch for glob-style pattern matching against TOP_LEVEL_EXCLUDE.
    This supports wildcards like "config.yaml.bak.*" to match any timestamped
    backup file.

    Returns True if the entry should be EXCLUDED.
    """
    for pattern in TOP_LEVEL_EXCLUDE:
        if fnmatch.fnmatch(name, pattern):
            return True
    return False


def redact_env_content(content: bytes) -> bytes:
    """Replace API key and secret values with [REDACTED] in .env file content.

    Parses each line looking for KEY=VALUE patterns where VALUE looks like
    a secret (API key, token, etc.). Matching values are replaced with the
    literal string "[REDACTED]". Non-matching lines pass through unchanged.

    Works on UTF-8 encoded bytes (what we read from disk) and returns bytes
    (what we write into the tar archive).
    """
    text = content.decode("utf-8", errors="replace")
    lines = []
    for line in text.splitlines():
        # Match lines like:  OPENAI_API_KEY=sk-abc123
        # or:                ANTHROPIC_API_KEY="sk-ant-..."
        # The regex captures the key= prefix and the value separately.
        m = re.match(r'^(\s*[A-Z_][A-Z0-9_]*\s*=\s*)(.+)$', line)
        if m:
            prefix = m.group(1)
            value = m.group(2).strip()
            # Only redact if the value passes the secret heuristic
            if _looks_like_secret(value):
                lines.append(f"{prefix}[REDACTED]")
                continue
        lines.append(line)
    return ("\n".join(lines) + "\n").encode("utf-8")


def _looks_like_secret(value: str) -> bool:
    """Heuristic: does a value string look like an API key, token, or secret?

    This is a BEST-EFFORT heuristic — it cannot guarantee perfect detection.
    It uses three signals, evaluated in order:

        1. KNOWN PREFIXES — OpenAI (sk-), Anthropic (sk-ant-), GitHub (ghp_),
           HuggingFace (hf_), xAI (xai-), Google (gsk_), DeepSeek (dsk_), etc.
        2. HIGH-ENTROPY STRINGS — values over 30 chars that are >80% alphanumeric
           or separator characters (looks like a random token)
        3. (reserved for future: keyword matching on variable name)

    Returns True if the value should be redacted.
    """
    # Normalize: strip surrounding whitespace and quotes
    value = value.strip().strip('"').strip("'")
    if not value:
        return False
    if len(value) < 8:
        return False

    # Signal 1: Known API key / token prefixes
    secret_prefixes = (
        "sk-", "sk_",       # OpenAI, Anthropic, and many others
        "eyJ",               # JWT tokens (base64-encoded JSON)
        "ghp_", "gho_", "ghu_", "ghs_",  # GitHub personal/oauth/user/server tokens
        "hf_",               # HuggingFace tokens
        "xai-",              # xAI / Grok tokens
        "gsk_",              # Google API secrets
        "dsk_",              # DeepSeek API keys
        "ak-",               # Generic access key prefix
    )
    if any(value.startswith(p) for p in secret_prefixes):
        return True

    # Signal 2: Long, random-looking strings (high entropy)
    # Most API keys are >30 characters of base64/hex-like data.
    if len(value) > 30:
        alpha_ratio = sum(c.isalnum() or c in "-_." for c in value) / max(len(value), 1)
        if alpha_ratio > 0.8:
            return True

    # Signal 3: Future — could check if variable name contains "token", "key",
    # "secret", but we don't have the variable name in this function.
    return False


# ── Import ───────────────────────────────────────────────────────────────────
# The import pipeline has three phases:
#   1. MANIFEST CHECK — read the embedded metadata, warn about redacted exports
#   2. CONFLICT SCAN  — check which files already exist on the target (unless --force)
#   3. EXTRACTION     — write files to the target Hermes home, restoring permissions
#
# Path resolution is the trickiest part: the archive stores paths like
# ".hermes/config.yaml" (relative to hermes_home.parent), and we need to
# map them to the TARGET Hermes home, which might be at a different location.
# ──────────────────────────────────────────────────────────────────────────────

def import_config(
    archive_path: str,
    dry_run: bool = False,
    force: bool = False,
    target_home: Optional[str] = None,
) -> None:
    """
    Import Hermes configuration from a tar.gz archive.

    Extracts files to the target Hermes home directory. By default,
    refuses to overwrite existing files (use --force to override).

    Parameters:
        archive_path - Path to the .tar.gz export archive
        dry_run      - If True, preview what WOULD happen without making changes
        force        - If True, overwrite existing files on the target
        target_home  - Override the target Hermes home (default: current host's ~/.hermes)

    Exit codes:
        0 - Success (or dry-run completed)
        1 - Error (archive not found, conflicts detected, etc.)
    """
    archive_path = Path(archive_path).expanduser().resolve()
    hermes_home = Path(target_home).expanduser().resolve() if target_home else get_hermes_home()

    # ── Validate archive exists ─────────────────────────────────────────────
    if not archive_path.exists():
        print(f"ERROR: Archive not found: {archive_path}")
        sys.exit(1)

    print(f"Archive:     {archive_path}")
    print(f"Target home: {hermes_home}")
    print(f"Mode:        {'dry-run' if dry_run else 'live'}{' (force)' if force else ''}")

    with _open_archive(archive_path) as tar:
        members = tar.getmembers()

        # ── Phase 1: Read the embedded manifest ──────────────────────────
        manifest = None
        for m in members:
            if m.name == ".hermes-migrate-manifest.json":
                manifest = json.loads(tar.extractfile(m).read())
                break

        if manifest:
            print(f"\nExport metadata:")
            print(f"  Created:    {manifest.get('exported_at', 'unknown')}")
            print(f"  From host:  {manifest.get('hostname', 'unknown')}")
            print(f"  Redacted:   {manifest.get('redacted', False)}")
            if manifest.get("redacted"):
                print("  *** WARNING: Secrets were redacted in this export. ***")
                print("  *** You'll need to fill in API keys manually.       ***")

        conflicts = []
        to_extract = []

        # ── Phase 2: Scan for conflicts and build the extraction list ────
        for m in members:
            if m.name == ".hermes-migrate-manifest.json":
                continue

            # ── Path resolution ──────────────────────────────────────────
            # The archive stores paths relative to the source's hermes_home.parent.
            # Example: if source was /home/alice/.hermes/config.yaml,
            # the archive arcname is ".hermes/config.yaml".
            #
            # We need to map this to the TARGET hermes home, which could be
            # at a completely different path (e.g., /opt/hermes/.hermes/).
            #
            # Strategy:
            #   - If the first path component is ".hermes", strip it and
            #     make the path relative to the target hermes_home.
            #   - Otherwise (legacy archives or dot-prefixed files), place
            #     them relative to hermes_home.parent.
            parts = Path(m.name).parts
            if parts[0] == ".hermes":
                # Standard case: .hermes/config.yaml → {target_home}/config.yaml
                rel_path = Path(*parts[1:]) if len(parts) > 1 else Path(".")
                target_path = hermes_home / rel_path
            elif parts[0].startswith("."):
                # Legacy/edge case: other dot-prefixed entries
                target_path = hermes_home.parent / m.name
            else:
                # Unusual: non-dot-prefixed entries at archive root
                target_path = hermes_home.parent / m.name

            # Directories are created immediately (mkdir -p behavior)
            if m.isdir():
                if not dry_run:
                    target_path.mkdir(parents=True, exist_ok=True)
                continue

            # File conflict detection — unless --force, flag conflicts
            if target_path.exists() and not force:
                conflicts.append((m.name, str(target_path)))
                continue

            to_extract.append((m, target_path))

        # ── Report conflicts and abort if any ────────────────────────────
        if conflicts:
            print(f"\n{len(conflicts)} file(s) already exist on target (use --force to overwrite):")
            for arcname, target in conflicts:
                print(f"  {arcname}  →  {target}")
            if not dry_run:
                print("\nAborting. Use --force to overwrite, or --dry-run to preview.")
                sys.exit(1)

        # ── Dry-run: just print what would happen ────────────────────────
        if dry_run:
            print(f"\nWould extract {len(to_extract)} file(s):")
            for m, target in sorted(to_extract, key=lambda x: str(x[1])):
                print(f"  {target}")
            return

        # ── Phase 3: Extract files to target ─────────────────────────────
        print(f"\nExtracting {len(to_extract)} file(s)...")
        for m, target_path in to_extract:
            # Ensure parent directories exist (for deeply nested files)
            target_path.parent.mkdir(parents=True, exist_ok=True)
            content = tar.extractfile(m).read()

            # Write the file and restore original permissions
            target_path.write_bytes(content)
            if m.mode:
                target_path.chmod(m.mode)

            print(f"  {target_path}")

    print(f"\nImport complete. {len(to_extract)} files restored to {hermes_home}")

    # ── Post-import reminders ────────────────────────────────────────────
    if manifest and manifest.get("redacted"):
        print("\n*** REMINDER: This export had secrets redacted. ***")
        print("*** Run 'hermes auth add <provider>' to re-authenticate each provider. ***")
        print("*** Or manually edit .env to fill in your API keys. ***")

    print("\nNext steps:")
    print("  1. Verify:  hermes config check")
    print("  2. Re-auth: hermes auth list    (re-authenticate OAuth providers)")
    print("  3. Test:    hermes doctor")
    print("  4. Restart gateway if running: hermes gateway restart")


# ── List ─────────────────────────────────────────────────────────────────────
# `hermes-migrate list <archive>` — inspect an archive without extracting it.
# Displays the embedded manifest metadata first, then a table of all contents
# with file/directory indicators and sizes.
# ──────────────────────────────────────────────────────────────────────────────

def list_archive(archive_path: str) -> None:
    """List the contents of an export archive without extracting.

    Shows:
        1. The embedded manifest (hostname, date, redaction status)
        2. All files and directories with type indicators and sizes

    Use this to preview what's in an archive before importing.
    """
    archive_path = Path(archive_path).expanduser().resolve()

    if not archive_path.exists():
        print(f"ERROR: Archive not found: {archive_path}")
        sys.exit(1)

    with _open_archive(archive_path) as tar:
        members = tar.getmembers()

        # Display the embedded manifest first (source host, date, etc.)
        for m in members:
            if m.name == ".hermes-migrate-manifest.json":
                manifest = json.loads(tar.extractfile(m).read())
                print("=== Export Manifest ===")
                for k, v in manifest.items():
                    print(f"  {k}: {v}")
                print()

        # Display contents table: [F] for files, [D] for directories
        # The count excludes the manifest entry itself
        print(f"=== Contents ({len([m for m in members if m.name != '.hermes-migrate-manifest.json'])} items) ===")
        for m in members:
            if m.name == ".hermes-migrate-manifest.json":
                continue
            type_char = "D" if m.isdir() else "F"
            size = _human_size(m.size) if m.isfile() else ""
            print(f"  [{type_char}] {m.name:60s} {size}")


# ── Diff ─────────────────────────────────────────────────────────────────────
# `hermes-migrate diff <archive>` — compare an archive against a target.
# Useful for seeing what would change BEFORE running an import.
#
# Output categories:
#   + New       — files in the archive that don't exist on target
#   ~ Different — files that exist on both sides but differ in content
#   = Identical — files that are byte-for-byte the same (no change needed)
# ──────────────────────────────────────────────────────────────────────────────

def diff_archive(archive_path: str, target_home: Optional[str] = None) -> None:
    """Compare an export archive against the current (or target) Hermes home.

    Shows what would be created, overwritten, or left unchanged if the
    archive were imported. Files >1MB are compared by size only (not content)
    to keep the operation fast.

    Note: This only compares files that exist IN the archive. It does not
    inventory the target for files that are present there but missing from
    the archive.
    """
    archive_path = Path(archive_path).expanduser().resolve()
    hermes_home = Path(target_home).expanduser().resolve() if target_home else get_hermes_home()

    if not archive_path.exists():
        print(f"ERROR: Archive not found: {archive_path}")
        sys.exit(1)

    print(f"Comparing archive {archive_path.name}")
    print(f"  against {hermes_home}\n")

    with _open_archive(archive_path) as tar:
        # Only compare regular files (skip directories and the manifest)
        members = [m for m in tar.getmembers()
                   if m.isfile() and m.name != ".hermes-migrate-manifest.json"]

        new_files = []       # In archive but not on target
        different = []       # On both sides but content differs
        identical = []       # Byte-for-byte identical

        for m in members:
            # Resolve target path using the same logic as import_config
            parts = Path(m.name).parts
            if parts[0] == ".hermes":
                rel_path = Path(*parts[1:]) if len(parts) > 1 else Path(".")
                target_path = hermes_home / rel_path
            else:
                target_path = hermes_home.parent / m.name

            # File doesn't exist on target → would be created
            if not target_path.exists():
                new_files.append(str(target_path))
                continue

            # File exists — compare content
            # For files >1MB, only compare size (reading full content would be slow)
            if m.size < 1_000_000:
                archive_content = tar.extractfile(m).read()
                target_content = target_path.read_bytes()
                if archive_content != target_content:
                    different.append(str(target_path))
                else:
                    identical.append(str(target_path))
            else:
                # Large file: compare by size only
                if m.size != target_path.stat().st_size:
                    different.append(f"{target_path} (size differs)")
                else:
                    identical.append(str(target_path))

    # ── Summary output ──────────────────────────────────────────────────
    print(f"  New (would be created):     {len(new_files)}")
    for f in sorted(new_files)[:20]:
        print(f"    + {f}")
    if len(new_files) > 20:
        print(f"    ... and {len(new_files) - 20} more")

    print(f"\n  Different (would overwrite): {len(different)}")
    for f in sorted(different)[:20]:
        print(f"    ~ {f}")
    if len(different) > 20:
        print(f"    ... and {len(different) - 20} more")

    print(f"\n  Identical (no change):       {len(identical)}")


# ── Helpers ──────────────────────────────────────────────────────────────────
# Utility functions shared across the module.
# ──────────────────────────────────────────────────────────────────────────────

def _human_size(size: int) -> str:
    """Format a byte count into a human-readable string.

    Examples:
        42       → "42 B"
        1536     → "1.5 KB"
        1048576  → "1.0 MB"
    """
    for unit in ("B", "KB", "MB", "GB"):
        if size < 1024:
            return f"{size:.1f} {unit}" if unit != "B" else f"{size} B"
        size /= 1024
    return f"{size:.1f} TB"


def _open_archive(archive_path: Path) -> tarfile.TarFile:
    """Open a tar.gz archive with graceful error handling.

    Wraps tarfile.open() to catch ReadError (corrupt archive, wrong format,
    truncated file) and exit with a clear error message instead of a traceback.
    """
    try:
        return tarfile.open(archive_path, "r:gz")
    except tarfile.ReadError as e:
        print(f"ERROR: Cannot read archive: {archive_path}")
        print(f"  {e}")
        print("  The file may be corrupt, not a valid tar.gz, or truncated.")
        sys.exit(1)


# ── Migrate ───────────────────────────────────────────────────────────────────
# `hermes-migrate migrate` — one-command host-to-host migration over SSH.
#
# The archive is created on the source, transferred to the destination via scp,
# then imported. The tool can be run from the source, the destination, or a
# third host. If Hermes isn't installed on the destination, it offers to install
# it (or auto-installs with --install).
#
# SSH is invoked via subprocess (ssh/scp) — no external Python deps needed.
# ──────────────────────────────────────────────────────────────────────────────

HERMES_INSTALL_CMD = (
    "curl -fsSL https://raw.githubusercontent.com/NousResearch/hermes-agent/"
    "main/scripts/install.sh | bash"
)

# Path where this script gets staged on remote hosts
REMOTE_SCRIPT_PATH = "/tmp/hermes_migrate.py"


def _is_localhost(host: str) -> bool:
    """Check whether a host specifier refers to the local machine.

    Handles: None, empty string, 'localhost', '127.0.0.1', '::1',
    and the machine's own hostname.
    """
    if not host:
        return True
    # Strip user@ prefix if present
    hostname = host.split("@")[-1]
    if hostname in ("localhost", "127.0.0.1", "::1"):
        return True
    try:
        if hostname == socket.gethostname():
            return True
    except Exception:
        pass
    return False


def _ssh_base_args(host: str) -> list[str]:
    """Build a base ssh/scp argument list with common safety options.

    Disables strict host key checking (needed for first-time connections)
    and sets a connection timeout. The host is user@host or just host.
    """
    return [
        "-o", "StrictHostKeyChecking=no",
        "-o", "UserKnownHostsFile=/dev/null",
        "-o", "ConnectTimeout=15",
        "-o", "BatchMode=no",
    ]


def _ssh_run(
    host: str,
    command: str,
    timeout: int = 300,
    capture: bool = True,
) -> subprocess.CompletedProcess:
    """Run a command on a remote host via SSH.

    Parameters:
        host    - Remote host (user@host or just host).
        command - Shell command to execute.
        timeout - Max seconds to wait for completion.
        capture - If True, capture stdout/stderr. If False, let them pass through.

    Returns the CompletedProcess. Exits with code 1 on SSH failure.
    """
    ssh_args = _ssh_base_args(host) + [host, command]
    try:
        result = subprocess.run(
            ["ssh"] + ssh_args,
            capture_output=capture,
            text=True,
            timeout=timeout,
        )
        if result.returncode != 0:
            print(f"ERROR: SSH command failed on {host}")
            print(f"  Command: {command}")
            if result.stderr:
                print(f"  stderr: {result.stderr.strip()}")
            sys.exit(1)
        return result
    except subprocess.TimeoutExpired:
        print(f"ERROR: SSH command timed out after {timeout}s on {host}")
        sys.exit(1)
    except FileNotFoundError:
        print("ERROR: 'ssh' command not found. Is OpenSSH client installed?")
        sys.exit(1)


def _scp_transfer(
    source: str,
    dest: str,
    timeout: int = 300,
) -> None:
    """Copy a file between hosts (or locally) via scp.

    Parameters:
        source - Source path, optionally prefixed with host: (e.g., 'host:/tmp/x.tar.gz')
        dest   - Destination path, optionally prefixed with host:
        timeout- Max seconds to wait.

    For local transfers (no host prefix on either side), uses cp instead of scp.
    """
    # Check if this is a local-to-local copy
    if ":" not in source and ":" not in dest:
        print(f"  cp {source} → {dest}")
        subprocess.run(["cp", source, dest], check=True, timeout=timeout)
        return

    scp_args = _ssh_base_args(source if ":" in source else dest)
    # scp needs args before the host:path specs
    print(f"  scp {source} → {dest}")
    try:
        subprocess.run(
            ["scp"] + scp_args + [source, dest],
            check=True,
            timeout=timeout,
        )
    except subprocess.CalledProcessError as e:
        print(f"ERROR: SCP transfer failed: {e}")
        sys.exit(1)
    except subprocess.TimeoutExpired:
        print(f"ERROR: SCP transfer timed out after {timeout}s")
        sys.exit(1)
    except FileNotFoundError:
        print("ERROR: 'scp' command not found. Is OpenSSH client installed?")
        sys.exit(1)


def _stage_script(host: str) -> None:
    """Copy this script to a remote host's /tmp/ so it can be run there.

    Skips if the host is localhost (script is already available locally).
    The script is self-contained (stdlib only, no Python deps), so it runs
    on any host with Python 3.10+.
    """
    if _is_localhost(host):
        return
    script_path = Path(__file__).resolve()
    print(f"  Copying migration script to {host}...")
    _scp_transfer(
        str(script_path),
        f"{host}:{REMOTE_SCRIPT_PATH}",
        timeout=30,
    )


def _remote_export(
    host: str,
    output_path: str,
    redact_secrets: bool = False,
    no_profiles: bool = False,
) -> None:
    """Export Hermes config on a remote host by running this script via SSH.

    Parameters:
        host           - Remote host (user@host).
        output_path    - Path ON THE REMOTE HOST for the archive.
        redact_secrets - Pass --redact-secrets to the remote export.
        no_profiles    - Pass --no-profiles to the remote export.
    """
    cmd_parts = [f"python3 {REMOTE_SCRIPT_PATH}", "export", "-o", output_path]
    if redact_secrets:
        cmd_parts.append("--redact-secrets")
    if no_profiles:
        cmd_parts.append("--no-profiles")
    cmd = " ".join(cmd_parts)

    print(f"\n  Exporting from {host}...")
    _ssh_run(host, cmd, timeout=120)
    print(f"  Export complete on {host}")


def _remote_import(
    host: str,
    archive_path: str,
    target_home: Optional[str] = None,
) -> None:
    """Import an archive on a remote host via SSH.

    Parameters:
        host         - Remote host (user@host).
        archive_path - Path ON THE REMOTE HOST to the archive.
        target_home  - Optional target Hermes home directory.
    """
    cmd_parts = [f"python3 {REMOTE_SCRIPT_PATH}", "import", archive_path, "--force"]
    if target_home:
        cmd_parts.append(f"--target-home {target_home}")
    cmd = " ".join(cmd_parts)
    print(f"\n  Importing on {host}...")
    _ssh_run(host, cmd, timeout=120)
    print(f"  Import complete on {host}")


def _remote_cleanup(host: str, *paths: str) -> None:
    """Remove temp files on a remote host via SSH."""
    if not paths:
        return
    cmd = f"rm -f {' '.join(paths)}"
    try:
        _ssh_run(host, cmd, timeout=10)
    except SystemExit:
        # Cleanup failures are non-fatal — just warn
        print(f"  (warning: cleanup on {host} failed, temp files may remain)")


def _check_hermes_installed(host: str) -> bool:
    """Check whether Hermes is installed on a host.

    Works for both local and remote hosts. Returns True if 'hermes'
    is found on PATH.
    """
    if _is_localhost(host):
        # Local check: just look for hermes on PATH
        try:
            subprocess.run(
                ["which", "hermes"],
                capture_output=True,
                timeout=5,
            )
            return True
        except (subprocess.CalledProcessError, FileNotFoundError):
            pass
        # Also check if ~/.hermes exists (installed but not on PATH)
        if (Path.home() / ".hermes").exists():
            return True
        return False
    else:
        # Remote check via SSH
        result = _ssh_run(host, "which hermes || test -d ~/.hermes && echo found", timeout=10)
        return result.returncode == 0 and result.stdout.strip() != ""


def _install_hermes(host: str, auto_install: bool = False) -> bool:
    """Install Hermes on a host if it isn't already present.

    Parameters:
        host         - Host to install on (user@host or localhost).
        auto_install - If True, install without prompting. If False,
                       prompt the user before proceeding.

    Returns True if Hermes is now installed (or was already).
    Exits if the user declines installation.
    """
    if _check_hermes_installed(host):
        return True

    label = "this machine" if _is_localhost(host) else host

    if not auto_install:
        print(f"\nHermes is not installed on {label}.")
        response = input("Install Hermes now? [Y/n] ").strip().lower()
        if response and response not in ("y", "yes"):
            print("Aborting. Install Hermes on the destination first, or re-run with --install.")
            sys.exit(1)

    print(f"\nInstalling Hermes on {label}...")
    print(f"  Running: {HERMES_INSTALL_CMD}")

    if _is_localhost(host):
        # Local install
        try:
            subprocess.run(
                ["bash", "-c", HERMES_INSTALL_CMD],
                check=True,
                timeout=300,
            )
        except subprocess.CalledProcessError as e:
            print(f"ERROR: Hermes installation failed: {e}")
            sys.exit(1)
    else:
        # Remote install
        _ssh_run(host, HERMES_INSTALL_CMD, timeout=300, capture=False)

    print(f"  Installation complete on {label}")
    return True


def migrate_config(
    source: Optional[str] = None,
    dest: Optional[str] = None,
    install: bool = False,
    redact_secrets: bool = False,
    no_profiles: bool = False,
    target_home: Optional[str] = None,
) -> None:
    """One-command migration from source host to destination host over SSH.

    Can be run from the source, the destination, or a third host. The tool
    exports Hermes config from the source, transfers the archive to the
    destination via scp, and imports it. If Hermes is not installed on the
    destination, it offers to install it (or auto-installs with --install).

    Parameters:
        source         - Source host (user@host or None for localhost).
        dest           - Destination host (user@host or None for localhost).
        install        - Auto-install Hermes on dest if missing (skip prompt).
        redact_secrets - Redact API keys during transfer.
        no_profiles    - Exclude named profiles from migration.

    At least one of source/dest must be remote for this to be useful;
    if both are local, falls back to a local export-then-import.
    """
    source = source or ""
    dest = dest or ""

    source_is_local = _is_localhost(source)
    dest_is_local = _is_localhost(dest)

    # ── Validate ─────────────────────────────────────────────────────────
    if not source and not dest:
        print("ERROR: At least one of --source or --dest is required.")
        print("  For local migration, use: hermes_migrate.py export + import")
        sys.exit(1)

    print("=" * 60)
    print("Hermes Migration")
    print(f"  Source:      {'localhost' if source_is_local else source}")
    print(f"  Destination: {'localhost' if dest_is_local else dest}")
    print(f"  Running from: {'source' if source_is_local else 'destination' if dest_is_local else 'third host'}")
    print("=" * 60)

    # ── Stage the script on remote hosts that need it ────────────────────
    if not source_is_local:
        _stage_script(source)
    if not dest_is_local and dest != source:
        _stage_script(dest)

    # ── Check/install Hermes on destination ──────────────────────────────
    if not _check_hermes_installed(dest if not dest_is_local else ""):
        # Note: _check_hermes_installed("") checks localhost
        target = dest if not dest_is_local else ""
        _install_hermes(target, auto_install=install)

    # ── 1. Export from source ────────────────────────────────────────────
    # The archive is always created on the source host.
    archive_name = f"hermes-migrate-{os.uname().nodename}-{datetime.now().strftime('%Y%m%d-%H%M%S')}.tar.gz"
    source_archive = f"/tmp/{archive_name}"

    if source_is_local:
        print(f"\nExporting from localhost...")
        export_config(
            output_path=source_archive,
            redact_secrets=redact_secrets,
            include_profiles=not no_profiles,
        )
    else:
        _remote_export(source, source_archive, redact_secrets, no_profiles)

    # ── 2. Transfer archive to destination ───────────────────────────────
    dest_archive = f"/tmp/{archive_name}"

    if source_is_local and dest_is_local:
        # Both local — archive is already in place, no transfer needed
        # (But use the correct path: source_archive and dest_archive are the same)
        pass
    elif source_is_local:
        # Source local, dest remote
        print(f"\nTransferring archive to {dest}...")
        _scp_transfer(source_archive, f"{dest}:{dest_archive}", timeout=120)
    elif dest_is_local:
        # Source remote, dest local
        print(f"\nTransferring archive from {source}...")
        _scp_transfer(f"{source}:{source_archive}", dest_archive, timeout=120)
    else:
        # Both remote (3rd host) — scp between them
        print(f"\nTransferring archive from {source} to {dest}...")
        _scp_transfer(
            f"{source}:{source_archive}",
            f"{dest}:{dest_archive}",
            timeout=120,
        )

    # ── 3. Import on destination ─────────────────────────────────────────
    if dest_is_local:
        print(f"\nImporting on localhost...")
        import_config(
            archive_path=dest_archive,
            force=True,
            target_home=target_home,
        )
    else:
        _remote_import(dest, dest_archive, target_home=target_home)

    # ── 4. Cleanup temp files ────────────────────────────────────────────
    print(f"\nCleaning up...")
    if not source_is_local:
        _remote_cleanup(source, source_archive, REMOTE_SCRIPT_PATH)
    else:
        # Clean local temp files
        for p in [source_archive]:
            try:
                Path(p).unlink(missing_ok=True)
            except Exception:
                pass

    if not dest_is_local:
        _remote_cleanup(dest, dest_archive, REMOTE_SCRIPT_PATH)
    else:
        for p in [dest_archive]:
            try:
                Path(p).unlink(missing_ok=True)
            except Exception:
                pass

    print(f"\n{'=' * 60}")
    print("Migration complete!")
    print(f"  {source if not source_is_local else 'localhost'} → {dest if not dest_is_local else 'localhost'}")
    print(f"\nOn the destination, run:")
    print(f"  hermes gateway restart")
    print(f"{'=' * 60}")


# ── CLI ──────────────────────────────────────────────────────────────────────
# Command-line interface using argparse with subcommands.
# Each subcommand maps directly to a top-level function:
#   export  → export_config()    import  → import_config()
#   list    → list_archive()     diff    → diff_archive()
#   migrate → migrate_config()
# ──────────────────────────────────────────────────────────────────────────────

def main():
    """Parse arguments and dispatch to the appropriate subcommand.

    This is the entry point when the script is run directly or via the
    'hermes-migrate' console script.
    """
    parser = argparse.ArgumentParser(
        description="Hermes Migrate — Export/Import Hermes Agent configurations.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  hermes-migrate export                                    # Export full config
  hermes-migrate export --redact-secrets                   # Export with API keys redacted
  hermes-migrate export -o backup.tar.gz                   # Custom output path
  hermes-migrate import backup.tar.gz                      # Import to current host
  hermes-migrate import backup.tar.gz --dry-run            # Preview what would happen
  hermes-migrate import backup.tar.gz --force              # Overwrite conflicts
  hermes-migrate list backup.tar.gz                        # List archive contents
  hermes-migrate diff backup.tar.gz                        # Compare archive vs current
  hermes-migrate migrate --source user@host1 --dest user@host2   # Host-to-host migration
        """,
    )
    parser.add_argument(
        "--version", action="version", version=f"%(prog)s {__version__}"
    )

    # Subcommands: each gets its own argument parser
    sub = parser.add_subparsers(dest="command", help="Command")

    # ── export ───────────────────────────────────────────────────────────
    p_export = sub.add_parser("export", help="Export Hermes configuration to archive")
    p_export.add_argument(
        "-o", "--output",
        help="Output archive path (default: hermes-export-<host>-<date>.tar.gz)",
    )
    p_export.add_argument(
        "--redact-secrets",
        action="store_true",
        help="Replace API keys/secrets with [REDACTED] in the export",
    )
    p_export.add_argument(
        "--no-profiles",
        action="store_true",
        help="Exclude named profiles from the export",
    )
    p_export.add_argument(
        "--hermes-home",
        help=f"Path to Hermes home directory (default: {get_hermes_home()})",
    )

    # ── import ───────────────────────────────────────────────────────────
    p_import = sub.add_parser("import", help="Import Hermes configuration from archive")
    p_import.add_argument("archive", help="Path to the export archive (.tar.gz)")
    p_import.add_argument(
        "--dry-run",
        action="store_true",
        help="Show what would be imported without making changes",
    )
    p_import.add_argument(
        "--force",
        action="store_true",
        help="Overwrite existing files on target",
    )
    p_import.add_argument(
        "--target-home",
        help=f"Target Hermes home directory (default: {get_hermes_home()})",
    )

    # ── list ─────────────────────────────────────────────────────────────
    p_list = sub.add_parser("list", help="List contents of an export archive")
    p_list.add_argument("archive", help="Path to the export archive (.tar.gz)")

    # ── diff ─────────────────────────────────────────────────────────────
    p_diff = sub.add_parser("diff", help="Compare archive against current/target config")
    p_diff.add_argument("archive", help="Path to the export archive (.tar.gz)")
    p_diff.add_argument(
        "--target-home",
        help=f"Target Hermes home to compare against (default: {get_hermes_home()})",
    )

    # ── migrate ────────────────────────────────────────────────────────────
    p_migrate = sub.add_parser(
        "migrate",
        help="One-command host-to-host migration over SSH",
    )
    p_migrate.add_argument(
        "-s", "--source",
        help="Source host (user@host). Omit if running on source host.",
    )
    p_migrate.add_argument(
        "-d", "--dest",
        help="Destination host (user@host). Omit if running on destination host.",
    )
    p_migrate.add_argument(
        "-i", "--install",
        action="store_true",
        help="Auto-install Hermes on destination if missing (skip prompt)",
    )
    p_migrate.add_argument(
        "--redact-secrets",
        action="store_true",
        help="Redact API keys/secrets during transfer",
    )
    p_migrate.add_argument(
        "--no-profiles",
        action="store_true",
        help="Exclude named profiles from migration",
    )
    p_migrate.add_argument(
        "--target-home",
        help="Target Hermes home on destination (default: ~/.hermes)",
    )

    # ── Parse and dispatch ───────────────────────────────────────────────
    args = parser.parse_args()

    if not args.command:
        parser.print_help()
        sys.exit(1)

    if args.command == "export":
        export_config(
            output_path=args.output,
            redact_secrets=args.redact_secrets,
            include_profiles=not args.no_profiles,
            hermes_home=Path(args.hermes_home) if args.hermes_home else None,
        )
    elif args.command == "import":
        import_config(
            archive_path=args.archive,
            dry_run=args.dry_run,
            force=args.force,
            target_home=args.target_home,
        )
    elif args.command == "list":
        list_archive(args.archive)
    elif args.command == "diff":
        diff_archive(args.archive, target_home=args.target_home)
    elif args.command == "migrate":
        migrate_config(
            source=args.source,
            dest=args.dest,
            install=args.install,
            redact_secrets=args.redact_secrets,
            no_profiles=args.no_profiles,
            target_home=args.target_home,
        )


if __name__ == "__main__":
    main()
